### ISSUE TITLE
Rewriting Progress Tracking

### ISSUE THREAD

**Issue by felixarntz** [awsmug/torro-forms#348]
This issue is a list of things that still need to happen in order to complete the rewrite/refactoring process of the plugin. See https://github.com/awsmug/torro-forms/tree/refactoring

* [x] template tags
* [x] email notifications submodule
* [x] form settings module + related hooks
* [x] new module metabox hooks
* [x] flexible metabox table column width based on screen size
* [x] fixed sidebar in form builder
* [x] bug with field dependencies (fields don't show initially even though their dependency is active)
* [x] bug with metabox content (content from all tabs show simultaneously initially)
* [x] handle frontend stylesheet
* [x] request verification hooks
* [x] new security module
* [x] reCAPTCHA submodule
* [x] honeypot submodule
* [x] timetrap submodule
* [x] linkcount submodule
* [x] member invitations
* [x] form upload handler
* [x] implement form duplication
* [x] clipboard functionality for shortcode
* [x] make showing submissions for a single form more intuitive in list table
* [x] show submission status in edit view
* [x] show submission values in edit view
* [x] automatically delete incomplete submissions after X days
* [x] hooks for evaluators module
* [x] chart shortcode
* [x] migrate export functionality from entries submodule to submissions list table
* [x] general stats submodule
* [x] bar chart submodule
* [x] form meta migration (do NOT delete old data for a few more releases!)
* [x] form attachment statuses migration
* [x] settings migration
* [x] uninstallation routine
* [x] element types
* [x] handle multiple choice element types correctly in frontend submission handler
* [x] plugin-lib: prime caches for queries
* [x] Backbone form builder implementation
* [x] form builder hooks triggering
* [x] WP-CLI commands
* [ ] extension boilerplate
* [ ] dynamic mapping for API actions
* [x] template tags for elements

**Comment by tyrann0us** [comment]
I'm curious to test v1.0.0-beta.9!
