### ISSUE TITLE
Intruducing Double Opt-In

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#453]
## Issue Overview
For data privacy reasons, a double opt-in option will be introduced. 

## Todos
- [ ] Hook for interrupting completion of form.
- [ ] Double opt-in tab with enable and email field selection.
- [ ] Double opt-in component class.
- [ ] Email template for opt-in mail in global settings section.

**Comment by Krasskieke** [comment]
Hi mahype,
when is this Function ready to use, it would really help solving my solution. 

Regards

Christian
